# Generated by Django 4.2.3 on 2024-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("s_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("num_persons", models.PositiveIntegerField()),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("upi_id", models.CharField(max_length=50)),
            ],
        ),
    ]
