# Generated by Django 4.2.3 on 2024-02-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintest", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
